# This is workflow for jazzy distribution
name: jazzy

# Currently ros2ai supports all distribution with rolling branch, this is intentionally done.
# Unless it becomes necessary, we will keep the rolling branch for every distribution.
# So that we do not have, dependencies, backport, these maintenance extra cost.
on:
  push:
    branches: [ "rolling" ]
  pull_request:
    branches: [ "rolling" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # each job goes for each ros supported distribution.
  # each job description absorb the distribution dependency as much as possible,
  # so that build verification script can be agnostic from distribution dependency.

  build:
    runs-on: ubuntu-latest
    container:
      image: ros:jazzy
      env:
        ROS_DISTRO: jazzy
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build with ROS jazzy
        shell: bash
        run: |
          ./scripts/github_workflows.sh
